version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/nextjs_app
hooks:
  BeforeInstall:
    - location: scripts/install_node_pm2.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300  # Increased for Next.js startup
      runas: ubuntu  # Changed from root
  ValidateService:
    - location: scripts/validate_application.sh
      timeout: 60
      runas: ubuntu
permissions:
  - object: /var/www/nextjs_app
    owner: ubuntu
    group: ubuntu
    mode: 755