version: 0.2

phases:
  install:
    commands:
      - echo "Installing Node.js..."
      - curl -sL https://deb.nodesource.com/setup_16.x | bash -
      - apt-get install -y nodejs
      - echo "Checking Node.js and npm versions..."
      - node -v
      - npm -v
      - echo "Updating npm..."
      - npm install -g npm@latest || echo "npm update failed, continuing with existing version"
      - npm -v
      
  pre_build:
    commands:
      - echo "Installing project dependencies..."
      - npm install
      
  build:
    commands:
      - echo "Building project..."
      - npm run build
      
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'