version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm ci
      - npm cache clean --force

  pre_build:
    commands:
      - echo "Pre-build phase started on $(date)"
      - echo "Node.js $(node --version)"
      - echo "npm $(npm --version)"
      - echo "Project structure:"
      - ls -la

  build:
    commands:
      - echo "Build started on $(date)"
      - export NODE_OPTIONS="--max-old-space-size=4096"
      - npm run build --verbose
      - echo "Build output:"
      - ls -la .next/

  post_build:
    commands:
      - echo "Preparing artifacts..."
      - chmod +x scripts/*.sh  # Ensure scripts are executable
      - echo "Final directory structure:"
      - ls -la
      - echo "Build completed on $(date)"

artifacts:
  files:
    - "**/*"  # Include all files
  base-directory: .  # Root of the project
  discard-paths: no  # Keep directory structure