version: 0.2

phases:
  install:
    commands:
      - echo "Updating package lists..."
      - apt-get update -y
      
      - echo "Installing Node.js..."
      - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      - apt-get install -y nodejs
      
      - echo "Installing latest npm..."
      - npm install -g npm@latest
      
      - echo "Versions:"
      - node -v
      - npm -v

  pre_build:
    commands:
      - echo "Installing project dependencies..."
      - npm ci --no-audit

  build:
    commands:
      - echo "Building Next.js application..."
      - npm run build

  post_build:
    commands:
      - echo "Copying build artifacts..."
      - mkdir -p $CODEBUILD_OUTPUT_DIR
      - cp -r .next public package.json package-lock.json appspec.yaml scripts/ $CODEBUILD_OUTPUT_DIR/

artifacts:
  files:
    - '**/*'
  base-directory: $CODEBUILD_OUTPUT_DIR