version: 0.2

phases:
  install:
    commands:
      - echo "Checking system package manager..."
      - if command -v yum &> /dev/null; then
          echo "Using yum package manager";
          yum update -y;
          yum install -y curl;
        elif command -v apt-get &> /dev/null; then
          echo "Using apt package manager";
          apt-get update -y;
          apt-get install -y curl;
        else
          echo "No supported package manager found";
          exit 1;
        fi

      - echo "Installing Node.js..."
      - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      - if command -v yum &> /dev/null; then
          yum install -y nodejs;
        elif command -v apt-get &> /dev/null; then
          apt-get install -y nodejs;
        fi

      - echo "Updating npm..."
      - npm install -g npm@latest
      - node -v
      - npm -v

  pre_build:
    commands:
      - echo "Installing project dependencies..."
      - npm ci --no-audit

  build:
    commands:
      - echo "Building Next.js application..."
      - npm run build

  post_build:
    commands:
      - echo "Copying build artifacts..."
      - mkdir -p $CODEBUILD_OUTPUT_DIR
      - cp -r .next public package.json package-lock.json appspec.yaml scripts/ $CODEBUILD_OUTPUT_DIR/

artifacts:
  files:
    - '**/*'
  base-directory: $CODEBUILD_OUTPUT_DIR